version: '3'

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: "PgAdmin2021!"
    ports:
      - "15432:5432"
    networks:
      - client-application-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "hugo.moraes@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2021!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    networks:
      - client-application-network
      
  client-api:
    build:
      context: ./images
      dockerfile: clients.dockerfile
    image: api/clients
    container_name: clients-api
    links:
      - postgres-db
    environment:
      - JDBC_URL=jdbc:postgresql://postgres-db:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
    networks:
      - client-application-network  
  

networks: 
  client-application-network:
    driver: bridge
